// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHjRn6BBjwtssVriZsKDP2BCVO-TWaLw',
    appId: '1:29404618400:web:5af054311b1dfe717733c5',
    messagingSenderId: '29404618400',
    projectId: 'fir-project-5a32b',
    authDomain: 'fir-project-5a32b.firebaseapp.com',
    storageBucket: 'fir-project-5a32b.firebasestorage.app',
    measurementId: 'G-YG2MF2J9SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdo-VNTuFzwh4wYgvthOUAh9NXazUgPyk',
    appId: '1:29404618400:android:e75b6780356ea1637733c5',
    messagingSenderId: '29404618400',
    projectId: 'fir-project-5a32b',
    storageBucket: 'fir-project-5a32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAakD3Us4Z2bhE5J1BZ2FDqfTXhfg8r1XY',
    appId: '1:29404618400:ios:13e9b05a1726471d7733c5',
    messagingSenderId: '29404618400',
    projectId: 'fir-project-5a32b',
    storageBucket: 'fir-project-5a32b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAakD3Us4Z2bhE5J1BZ2FDqfTXhfg8r1XY',
    appId: '1:29404618400:ios:13e9b05a1726471d7733c5',
    messagingSenderId: '29404618400',
    projectId: 'fir-project-5a32b',
    storageBucket: 'fir-project-5a32b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEHjRn6BBjwtssVriZsKDP2BCVO-TWaLw',
    appId: '1:29404618400:web:f00aeb06238b60b27733c5',
    messagingSenderId: '29404618400',
    projectId: 'fir-project-5a32b',
    authDomain: 'fir-project-5a32b.firebaseapp.com',
    storageBucket: 'fir-project-5a32b.firebasestorage.app',
    measurementId: 'G-9ZBGED02NX',
  );
}
